from typing import Dict, List

# Dictionary of synonyms and variations mapped to canonical schema column names
COLUMN_ALIASES: Dict[str, List[str]] = {
    # Monetary Amount fields
    "amount": [
        "invoice_value",
        "invoice_amount",
        "inv_amount",
        "payment_amt",
        "payment_amount",
        "gross_value",
        "gross_amount",
        "total",
        "total_amount",
        "total_value",
        "amount_paid",
        "settlement_value",
        "settlement_amount",
        "net_amount",
        "net_payout",
        "txn_amount",
        "transaction_amount",
        "credit_amount",
        "debit_amount",
        "billed_amount",
        "charge_amount",
        "final_amount",
    ],
    # Date fields
    "invoice_date": [
        "inv_date",
        "bill_date",
        "billing_date",
        "invoice_created_at",
        "created_at",
        "created_date",
        "order_date",
        "date",
    ],
    "settlement_date": [
        "settled_at",
        "payout_date",
        "settle_date",
        "deposit_date",
        "value_date",
        "settled_date",
        "date",
    ],
    "txn_date": [
        "transaction_date",
        "trans_date",
        "posting_date",
        "booking_date",
        "value_date",
        "statement_date",
        "date",
    ],
    # Identifiers
    "invoice_id": [
        "inv_id",
        "invoice_number",
        "invoice_no",
        "inv_no",
        "bill_id",
        "bill_no",
        "receipt_id",
        "receipt_no",
        "document_number",
    ],
    "settlement_id": [
        "set_id",
        "payout_id",
        "settlement_ref",
        "batch_id",
        "disbursement_id",
        "payout_ref",
    ],
    "bank_txn_id": [
        "txn_id",
        "transaction_id",
        "bank_ref",
        "statement_id",
        "entry_id",
        "line_id",
        "seq_no",
    ],
    "order_id": [
        "order_number",
        "order_no",
        "ord_id",
        "ord_no",
        "merchant_order_id",
        "client_order_id",
        "po_number",
        "reference_id",
    ],
    "reference_number": [
        "utr",
        "utr_number",
        "utr_no",
        "bank_reference",
        "bank_ref_no",
        "rrn",
        "external_reference",
        "ref_no",
        "reference",
        "payment_reference",
        "cheque_no",
    ],
    # Status
    "status": [
        "txn_status",
        "payment_status",
        "order_status",
        "state",
        "settlement_status",
        "transaction_status",
    ],
    # Fees and Deductions
    "fees": [
        "mdr",
        "processing_fee",
        "processing_fees",
        "service_charge",
        "service_charges",
        "commission",
        "platform_fee",
        "convenience_fee",
        "gateway_fee",
        "charges",
    ],
    "gst": [
        "gst_amount",
        "gst_paid",
        "tax",
        "tax_amount",
        "service_tax",
        "igst",
        "cgst_sgst",
        "vat",
    ],
    "tds": [
        "tds_amount",
        "tds_deducted",
        "withholding_tax",
        "section_194o_tds",
        "194o_tds",
        "tax_deducted",
    ],
    # Descriptions & Customer
    "customer_name": [
        "customer",
        "client_name",
        "buyer_name",
        "user_name",
        "account_name",
        "billed_to",
        "payer_name",
    ],
    "description": [
        "narration",
        "particulars",
        "remarks",
        "details",
        "transaction_details",
        "memo",
        "statement_narration",
    ],
    "balance": [
        "running_balance",
        "closing_balance",
        "available_balance",
        "ledger_balance",
        "account_balance",
    ],
}
