from typing import Dict, List

# Dictionary of synonyms and variations mapped to canonical schema column names
COLUMN_ALIASES: Dict[str, List[str]] = {
    # Monetary Amount fields
    "amount": [
        "invoice_value",
        "invoice_amount",
        "inv_amount",
        "payment_amt",
        "payment_amount",
        "gross_value",
        "gross_amount",
        "total",
        "total_amount",
        "total_value",
        "amount_paid",
        "settlement_value",
        "settlement_amount",
        "net_amount",
        "net_payout",
        "txn_amount",
        "transaction_amount",
        "credit_amount",
        "debit_amount",
        "billed_amount",
        "charge_amount",
        "final_amount",
        "fare_amount",
        "net_settlement",
        "treatment_cost",
        "remittance_amount",
        "reload_amount",
        "net_wallet_payout",
        "semester_fee",
        "cod_amount",
        "net_cod_remittance",
        "total_invoice_val",
    ],
    # Date fields
    "invoice_date": [
        "inv_date",
        "bill_date",
        "billing_date",
        "invoice_created_at",
        "created_at",
        "created_date",
        "order_date",
        "date",
        "booking_date",
        "admission_date",
        "txn_timestamp",
        "registration_date",
        "dispatch_date",
    ],
    "settlement_date": [
        "settled_at",
        "payout_date",
        "settle_date",
        "deposit_date",
        "value_date",
        "settled_date",
        "date",
        "settlement_timestamp",
        "credit_date",
        "remittance_date",
    ],
    "txn_date": [
        "transaction_date",
        "trans_date",
        "posting_date",
        "booking_date",
        "value_date",
        "statement_date",
        "credit_date",
        "date",
    ],
    # Identifiers
    "invoice_id": [
        "inv_id",
        "invoice_number",
        "invoice_no",
        "inv_no",
        "bill_id",
        "bill_no",
        "receipt_id",
        "receipt_no",
        "document_number",
        "pnr_ticket_no",
        "claim_invoice_no",
        "wallet_txn_no",
        "fee_receipt_no",
        "waybill_no",
    ],
    "settlement_id": [
        "set_id",
        "payout_id",
        "settlement_ref",
        "batch_id",
        "disbursement_id",
        "payout_ref",
        "payout_batch_no",
        "payout_ref_id",
        "disbursement_no",
        "remittance_id",
    ],
    "bank_txn_id": [
        "txn_id",
        "transaction_id",
        "bank_ref",
        "statement_id",
        "entry_id",
        "line_id",
        "seq_no",
        "bank_id",
        "stmt_txn_id",
        "bank_line_id",
        "entry_ref",
        "txn_seq",
    ],
    "order_id": [
        "order_number",
        "order_no",
        "ord_id",
        "ord_no",
        "merchant_order_id",
        "client_order_id",
        "po_number",
        "reference_id",
        "table_order_id",
        "booking_id",
        "patient_id",
        "gamer_tag_id",
        "enrollment_id",
        "consignee_order_id",
    ],
    "reference_number": [
        "utr",
        "utr_number",
        "utr_no",
        "bank_reference",
        "bank_ref_no",
        "rrn",
        "external_reference",
        "ref_no",
        "reference",
        "payment_reference",
        "cheque_no",
        "bank_utr",
        "utr_ref",
        "cheque_or_utr",
    ],
    # Status
    "status": [
        "txn_status",
        "payment_status",
        "order_status",
        "state",
        "settlement_status",
        "transaction_status",
        "booking_status",
        "discharge_status",
        "fee_status",
        "delivery_status",
    ],
    # Fees and Deductions
    "fees": [
        "mdr",
        "processing_fee",
        "processing_fees",
        "service_charge",
        "service_charges",
        "commission",
        "platform_fee",
        "convenience_fee",
        "gateway_fee",
        "charges",
        "tpa_service_fee",
        "platform_commission",
        "bank_subvention_fee",
        "freight_charge",
    ],
    "gst": [
        "gst_amount",
        "gst_paid",
        "tax",
        "tax_amount",
        "service_tax",
        "igst",
        "cgst_sgst",
        "vat",
        "gst_deduction",
        "gst_28_percent",
        "tax_on_fee",
        "gst_18",
    ],
    "tds": [
        "tds_amount",
        "tds_deducted",
        "withholding_tax",
        "section_194o_tds",
        "194o_tds",
        "tax_deducted",
        "tds_194b_deduction",
        "tds_194c",
    ],
    # Descriptions & Customer
    "customer_name": [
        "customer",
        "client_name",
        "buyer_name",
        "user_name",
        "account_name",
        "billed_to",
        "payer_name",
        "guest_name",
        "passenger_name",
        "patient_name",
        "player_username",
        "student_name",
        "consignee_name",
        "client_entity_name",
    ],
    "description": [
        "narration",
        "particulars",
        "remarks",
        "details",
        "transaction_details",
        "memo",
        "statement_narration",
        "memo_text",
    ],
    "balance": [
        "running_balance",
        "closing_balance",
        "available_balance",
        "ledger_balance",
        "account_balance",
        "available_funds",
    ],
}
