"""initial_schema

Revision ID: c0cde462859c
Revises: 
Create Date: 2026-09-03 22:33:26.284682

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c0cde462859c'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('reconciliation_jobs',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('org_id', sa.String(length=100), nullable=False),
    sa.Column('batch_id', sa.String(length=36), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('stage', sa.String(length=50), nullable=False),
    sa.Column('progress', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('result_payload', sa.JSON(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['batch_id'], ['batches.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_jobs_batch_id', 'reconciliation_jobs', ['batch_id'], unique=False)
    op.create_index('idx_jobs_org_id', 'reconciliation_jobs', ['org_id'], unique=False)
    op.create_index('idx_jobs_status', 'reconciliation_jobs', ['status'], unique=False)
    op.create_index(op.f('ix_reconciliation_jobs_org_id'), 'reconciliation_jobs', ['org_id'], unique=False)
    op.create_unique_constraint('uq_records_batch_txn_source', 'records', ['batch_id', 'transaction_id', 'source_type'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_records_batch_txn_source', 'records', type_='unique')
    op.drop_index(op.f('ix_reconciliation_jobs_org_id'), table_name='reconciliation_jobs')
    op.drop_index('idx_jobs_status', table_name='reconciliation_jobs')
    op.drop_index('idx_jobs_org_id', table_name='reconciliation_jobs')
    op.drop_index('idx_jobs_batch_id', table_name='reconciliation_jobs')
    op.drop_table('reconciliation_jobs')
    # ### end Alembic commands ###
